accounts/urls.py
from django.conf.urls import url
from accounts.views import AccountsLoginView, AccountsLogoutView, RegisterView, AccountsIndexView, UpdateUserView, \
    AddRealEstateView

urlpatterns = [
    url(r'^minhaconta/$', AccountsIndexView.as_view(), name='index'),
    url(r'^minhaconta/editar/$', UpdateUserView.as_view(), name='update_user'),
    url(r'^minhaconta/anunciar/$', AddRealEstateView.as_view(), name='add_real_estate'),
    url(r'^login/$', AccountsLoginView.as_view(), name='login'),
    url(r'^logout/$', AccountsLogoutView.as_view(), name='logout'),
    url(r'^registrar/$', RegisterView.as_view(), name='register'),
]

catalog/urls.py
from django.conf.urls import url
from catalog.views import RealEstateBuyListView, RealEstateRentListView

urlpatterns = [
    url(r'^comprar/(?P<state>[\w]+)/(?P<slug>[\w-]+)/$',
        RealEstateBuyListView.as_view(),
        name='list_real_state_buy_param'
        ),

    url(r'^comprar/$',
        RealEstateBuyListView.as_view(),
        name='list_real_state_buy'
        ),

    url(r'^alugar/(?P<state>[\w]+)/(?P<slug>[\w-]+)/$',
        RealEstateRentListView.as_view(),
        name='list_real_state_rent_param'
        ),

    url(r'^alugar/$', RealEstateRentListView.as_view(), name='list_real_state_rent'), ]

imovelweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^contas/', include('accounts.urls', namespace='accounts')),
    url(r'^imoveis/', include('catalog.urls', namespace='catalog')),
    url(r'^imovel/', include('realestate.urls', namespace='realestate')),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
import re
from django.core import validators
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/ ./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )

    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    created_at = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        name = str(self)
        if name:
            return name.split(" ")[0]
        return ""

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class UserAdminCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'name', 'email']


class UserAdminForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

accounts/views.py
from django.shortcuts import resolve_url as r, render
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.models import RealEstate
from realestate.forms import RealEstateCreationForm, AddressForm
from .forms import UserAdminCreationForm

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class AccountsIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/index.html'


class AccountsLoginView(LoginView):
    template_name = 'accounts/login.html'


class AccountsLogoutView(LogoutView):
    template_name = 'accounts/login.html'


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class AddRealEstateView(LoginRequiredMixin, CreateView):
    model = RealEstate
    template_name = 'accounts/add_real_estate.html'
    form_class = RealEstateCreationForm
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        address_form = AddressForm(request.POST)

        if not address_form.is_valid():
            return render(request, 'accounts/add_real_estate.html', {'form': address_form})

        address = address_form.save(commit=False)
        real_estate_form = RealEstateCreationForm(request.POST)
        real_estate_form.fields['address'] = address
        # real_estate_form.fields['seller'] = User.objects.get(id=7)

        if not real_estate_form.is_valid():
            return render(request, 'accounts/add_real_estate.html', {'form': real_estate_form})

        # real_estate_form.fields.seller =
        real_estate_form.save()


        # address = address_form.save()

        # real_estate_form.save()
        # if form.is_valid():
        #     data = {
        #         'real_state': form.data
        #     }
        #
        #     data['real_estate']['address']['number'] = form.number
        #     data['real_estate']['address']['neighborhood'] = form.neighborhood
        #     data['real_estate']['address']['postal_code'] = form.postal_code
        #     data['real_estate']['address']['city'] = form.city
        #
        #     real_estate = RealEstate(data)
        #     real_estate.save()
        #     # property.owner = request.user
        #     # property.image = request.FILES['image']
        #     # property.save()
        #     return redirect(r('realestate:show_real_estate', real_estate_id=real_estate.id))
        return super().post(request, *args, **kwargs)

accounts/templates/accounts/add_real_estate.html
{% extends 'accounts/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block custom_css %}
    <link href="{% static 'css/add_real_estate.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Minha conta | Editar dados{% endblock %}

{% block accounts_content %}
    <div id="add-real-estate-box" class="col-md-8">
        <form class="form-horizontal" method="post" novalidate="">
            {% csrf_token %}

            <input type="hidden" name="seller_id" value="{{ user.id }}">
            <div class="col-md-10">
                {% for error in form.errors %}
                    <small>{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-md-10">
                {% for error in form.non_field_errors %}
                    <small>{{ error }}</small>
                {% endfor %}
            </div>


            <div class="row">
                <h4>Preencha o endereço</h4>
                <hr>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="{{ form.street.id_for_label }}">Rua</label>
                        {% render_field form.street class="form-control" %}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.neighborhood.id_for_label }}">Bairro</label>
                        {% render_field form.neighborhood class="form-control" %}
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.number.id_for_label }}">Número</label>
                        {% render_field form.number class="form-control" %}
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="form-group">
                        <label for="{{ form.city.id_for_label }}">Cidade</label>
                        {% render_field form.city class="form-control" %}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.postal_code.id_for_label }}">Código Postal</label>
                        {% render_field form.postal_code class="form-control" %}
                    </div>
                </div>
            </div>

            <div class="row">
                <h4>Descreva o imóvel</h4>
                <hr>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.type.id_for_label }}">{{ form.type.label }}</label>
                        {% render_field form.type class="form-control" %}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.transaction_type.id_for_label }}">{{ form.transaction_type.label }}</label>
                        {% render_field form.transaction_type class="form-control" %}
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                {% render_field form.title class="form-control" %}
            </div>

            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                {% render_field form.description class="form-control" %}
            </div>

            <div class="row">
                <h4>Preencha as características</h4>
                <hr>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.sell_price.id_for_label }}">{{ form.sell_price.label }}</label>
                        {% render_field form.sell_price class="form-control" %}
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.rent_price.id_for_label }}">{{ form.rent_price.label }}</label>
                        {% render_field form.rent_price class="form-control" %}
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.condo_price.id_for_label }}">{{ form.condo_price.label }}</label>
                        {% render_field form.condo_price class="form-control" %}
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="{{ form.tax.id_for_label }}">{{ form.tax.label }}</label>
                        {% render_field form.tax class="form-control" %}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.area.id_for_label }}">{{ form.area.label }} m2</label>
                        {% render_field form.area class="form-control" %}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="{{ form.number_of_rooms.id_for_label }}">{{ form.number_of_rooms.label }}</label>
                        {% render_field form.number_of_rooms class="form-control" %}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="{{ form.number_of_bathrooms.id_for_label }}">{{ form.number_of_bathrooms.label }}</label>
                        {% render_field form.number_of_bathrooms class="form-control" %}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="{{ form.number_of_suites.id_for_label }}">{{ form.number_of_suites.label }}</label>
                        {% render_field form.number_of_suites class="form-control" %}
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="{{ form.number_of_car_parks.id_for_label }}">{{ form.number_of_car_parks.label }}</label>
                        {% render_field form.number_of_car_parks class="form-control" %}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-success btn-block col-md-12" type="submit">Salvar</button>
                </div>
            </div>
        </form>
    </div>


    {#    <div class="col-md-8">#}
    {#        <form class="form-horizontal" method="post" novalidate>#}
    {#            {% csrf_token %}#}
    {#            <fieldset>#}
    {#                {% for field in form %}#}
    {#                    <div class="form-group{% if field.errors %} has-error{% endif %}">#}
    {#                        <label class="register-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>#}
    {#                        {% render_field field class="form-control" %}#}
    {##}
    {#                        {% for error in field.errors %}#}
    {#                            <span class="help-block">{{ error }}</span>#}
    {#                        {% endfor %}#}
    {#                    </div>#}
    {#                {% endfor %}#}
    {#            </fieldset>#}
    {#            <button class="btn btn-success btn-block col-md-4" type="submit">Salvar</button>#}
    {#        </form>#}
    {#    </div>#}

{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Minha conta{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}">Início</a></li>
                    <li>Minha Conta</li>
                </ol>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <div class="list-group">
                    <a href="{% url 'accounts:index' %}" class="list-group-item active">
                        Minha Conta
                    </a>
                    <a href="{% url 'accounts:update_user' %}" class="list-group-item">
                        Editar Dados
                    </a>
                    <a href="#" class="list-group-item">
                        Anunciar
                    </a>
                </div>
            </div>

            <div class="col-md-8">
                {% block accounts_content %}
                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block custom_css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 login-box">

                <form class="form-signin" method="post" novalidate>
                    {% csrf_token %}

                    <h2 class="form-signin-heading">Entrar</h2>

                    <div class="login-error-box">
                        {% for error in form.non_field_errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>

                    <div class="form-group{% if form.username.errors %} has-error{% endif %}">

                        <label for="{{ form.username.auto_id }}"
                               class="login-form-label">{{ form.username.label }}</label>
                        {% render_field form.username class="form-control" %}

                        {% for error in form.username.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <label for="{{ form.password.auto_id }}"
                               class="login-form-label">{{ form.password.label }}</label>
                        {% render_field form.password class="form-control" %}
                        {{ field.password.errors }}
                        {% for error in form.password.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Sign in</button>
                </form>

            </div>
        </div>


        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                Não tem uma conta? <a href="{% url 'accounts:register' %}">Registre-se!</a>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block custom_css %}
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 register-box">
                <form class="form-signin" method="post" novalidate>
                    {% csrf_token %}

                    <h2 class="form-signin-heading">Registro</h2>

                    <div class="register-error-box">
                        {% for error in form.non_field_errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>

                    {% for field in form %}
                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                            <label class="register-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                            {% render_field field class="form-control" %}

                            {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary btn-block" type="submit">Registrar</button>
                </form>
            </div>

        </div>


    </div>

{% endblock %}

accounts/templates/accounts/update_user.html
{% extends 'accounts/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Minha conta | Editar dados{% endblock %}

{% block accounts_content %}

    <div class="col-md-4">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label class="register-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                        {% render_field field class="form-control" %}

                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endfor %}
            </fieldset>
            <button class="btn btn-success btn-block col-md-4" type="submit">Salvar</button>
        </form>
    </div>

{% endblock %}