accounts/urls.py
from django.conf.urls import url
from accounts.views import AccountsLoginView, AccountsLogoutView, RegisterView, AccountsIndexView, UpdateUserView, \
    AddRealEstateView

urlpatterns = [
    url(r'^minhaconta/$', AccountsIndexView.as_view(), name='index'),
    url(r'^minhaconta/editar/$', UpdateUserView.as_view(), name='update_user'),
    url(r'^minhaconta/anunciar/$', AddRealEstateView.as_view(), name='add_real_estate'),
    url(r'^login/$', AccountsLoginView.as_view(), name='login'),
    url(r'^logout/$', AccountsLogoutView.as_view(), name='logout'),
    url(r'^registrar/$', RegisterView.as_view(), name='register'),
]

catalog/urls.py
from django.conf.urls import url
from catalog.views import RealEstateBuyListView, RealEstateRentListView

urlpatterns = [
    url(r'^comprar/(?P<state>[\w]+)/(?P<slug>[\w-]+)/$',
        RealEstateBuyListView.as_view(),
        name='list_real_state_buy_param'
        ),

    url(r'^comprar/$',
        RealEstateBuyListView.as_view(),
        name='list_real_state_buy'
        ),

    url(r'^alugar/(?P<state>[\w]+)/(?P<slug>[\w-]+)/$',
        RealEstateRentListView.as_view(),
        name='list_real_state_rent_param'
        ),

    url(r'^alugar/$', RealEstateRentListView.as_view(), name='list_real_state_rent'), ]

imovelweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^contas/', include('accounts.urls', namespace='accounts')),
    url(r'^imoveis/', include('catalog.urls', namespace='catalog')),
    url(r'^imovel/', include('realestate.urls', namespace='realestate')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
import uuid
from django.shortcuts import resolve_url as r
from django.db import models

# Transaction Types
from accounts.models import User

SELL = 'S'
RENT = 'R'
ANY = 'A'

# Real Estate Types
LAND = 'L'
HOUSE = 'H'
APARTMENT = 'A'
FLAT = 'F'
PENTHOUSE = 'P'
KITNET = 'K'


class Address(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    street = models.CharField('Endereço', max_length=255)
    number = models.CharField('Número', max_length=5, blank=True, null=True)
    city = models.ForeignKey('catalog.City', verbose_name='Cidade')
    postal_code = models.CharField('CEP', max_length=10, blank=True, null=True)
    neighborhood = models.CharField('Bairro', max_length=30)

    def __str__(self):
        return "{}, {} - {}/{} ".format(self.street, self.number, self.city.name, self.city.state.abbreviation)


class RealEstate(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    TYPES = (
        (LAND, 'Terreno'),
        (HOUSE, 'Casa'),
        (APARTMENT, 'Apartamento'),
        (FLAT, 'Flat'),
        (PENTHOUSE, 'Terreno'),
        (KITNET, 'Kitnet'),
    )
    type = models.CharField('Tipo', max_length=1, choices=TYPES)

    TRANSACTION_TYPES = (
        (SELL, 'Venda'),
        (RENT, 'Aluguel'),
        (ANY, 'Venda ou Aluguel')
    )
    transaction_type = models.CharField('Tipo de Operação', max_length=1, choices=TRANSACTION_TYPES)

    address = models.ForeignKey(Address, related_name='address')
    # seller = models.ForeignKey(User, related_name='seller', verbose_name='Anunciante')

    title = models.CharField('Título', max_length=50)
    description = models.TextField('Descrição')
    sell_price = models.DecimalField('Venda', decimal_places=2, max_digits=10, null=True, blank=True)
    rent_price = models.DecimalField('Aluguel', decimal_places=2, max_digits=8, null=True, blank=True)
    area = models.IntegerField('Área')
    tax = models.DecimalField('IPTU', decimal_places=2, max_digits=8, null=True, blank=True)
    condo_price = models.DecimalField('Condomínio', decimal_places=2, max_digits=8, null=True, blank=True)
    number_of_rooms = models.IntegerField('Quartos')
    number_of_bathrooms = models.IntegerField('Banheiros')
    number_of_suites = models.IntegerField('Suítes')
    number_of_car_parks = models.IntegerField('Vagas')
    sold = models.BooleanField('Vendido', default=False)
    sold_at = models.DateTimeField('Vendido em', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    class Meta:
        verbose_name = 'Imóvel'
        verbose_name_plural = 'Imóveis'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return r('show_real_estate', real_estate_id=self.id)


# ToDo: Características: mobiliado, churrasqueira, espaço gourmet, etc..
# ToDo: Upload de Imagens
# class Photo(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
#     path = models.CharField(max_length=255)
#     default = models.BooleanField(default=False)


class Contact(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    code = models.CharField('DDD', max_length=5)
    number = models.CharField('Número', max_length=20)

    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

    def __str__(self):
        return "{}-{}".format(self.code, self.number)


class City(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField('Nome', max_length=80)
    slug = models.SlugField('Slug', unique=True)
    state = models.ForeignKey('catalog.State', verbose_name='Estado')
    capital = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_search_url(self):
        return r('list_real_state_buy_param', state=self.state.abbreviation.lower(), slug=self.slug)


class State(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField('Nome', max_length=50)
    abbreviation = models.CharField('UF', max_length=2, unique=True)

    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'
        ordering = ['name']

    def __str__(self):
        return self.name

core/views.py
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model
from catalog.models import City, RealEstate

User = get_user_model()


class HomePageView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cities = City.objects.filter(capital=True)
        real_estates = RealEstate.objects.all()[:6]
        context['grouped_real_estates'] = self.to_groups(real_estates, 3)
        context['grouped_cities'] = self.to_groups(cities, 3)
        return context

    def to_groups(self, element_list, number):
        for i in range(0, len(element_list), number):
            yield element_list[i:i + number]

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    <title>{% block title %}ImovelWeb{% endblock %}</title>
    <link href="{% static 'lib/bootswatch/css/bootswatch.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'lib/bootstrap/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

    {% block custom_css %}
    {% endblock %}
</head>
<body>
{% include 'nav.html' %}

{% block content %}
{% endblock %}

<div class="container marketing">
    <hr class="featurette-divider">
    <footer>
        <p class="pull-right"><a href="#">Topo</a></p>
        <p>© 2017 ImovelWeb, Inc. · <a href="#">Privacidade</a> · <a href="#">Termos</a></p>
    </footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
    <link href="{% static 'lib/bootstrap/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="searchSection" class="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="" src="{% static 'img/home-room.png' %}" alt="">
                <div class="container">
                    <div id="search-box-home" class="carousel-caption">
                        <h1>Encontre o imóvel dos seus sonhos</h1>
                        <div class="row center-block">
                            <div class="col-md-12">
                                <form>
                                    <div class="col-md-2 joint">
                                        <select class="form-control">
                                            <option>Comprar</option>
                                            <option>Alugar</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2 joint">
                                        <select class="form-control">
                                            <option>Todos</option>
                                            <option>Casa</option>
                                            <option>Apartamento</option>
                                            <option>Flat</option>
                                            <option>Cobertura</option>
                                            <option>Kitnet</option>
                                            <option>Sobrado</option>
                                        </select>
                                    </div>
                                    <div class="col-md-6 joint">
                                        <input type="text" class="form-control col-md-12" id=""
                                               placeholder="Digite sua cidade...">
                                    </div>
                                    <div class="col-md-2 joint">
                                        <button type="submit" class="btn btn-success col-md-12">Buscar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container marketing">
        {% if grouped_real_estates.count %}
            <div class="row suggestions-row">
                <div class="col-md-5 col-md-offset-4">
                    <h2>Algumas sugestões para você</h2>
                </div>
            </div>
            {% for grouped_properties in grouped_real_estates %}
                <div class="row">
                    <h4>{{ real_estate.title }}</h4>
                    {% for real_estate in grouped_properties %}
                        <div class="col-lg-4">
                            <img class="img-thumbnail"
                                 src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                                 alt="Generic placeholder image" width="140" height="140">
                            <h4>{{ real_estate.title }}</h4>
                            <ul class="list-unstyled">
                                <li>{{ real_estate.address.city }}
                                    - {{ real_estate.address.city.state.abbreviation }}</li>
                                <li>{{ real_estate.address.neighborhood }}</li>
                                <li>{{ real_estate.area }} m²</li>
                                <li>{{ real_estate.numberOfRooms }} quartos</li>

                                {% if real_estate.numberOfCarParks > 0 %}
                                    <li>{{ real_estate.numberOfCarParks }} {% if real_estate.numberOfCarParks == 1 %}
                                        vaga{% else %}vagas{% endif %} de garagem
                                    </li>
                                {% endif %}
                            </ul>
                            <p><a class="btn btn-warning" href="{{ real_estate.get_absolute_url }}" role="button">Ver
                                detalhes »</a></p>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% endif %}

        <!-- /.row -->
        <div class="row want-box">
            <div class="col-md-12">
                <div class="col-md-3 col-md-offset-3">
                    <a class="btn center-block btn-primary btn-lg" href="{% url 'catalog:list_real_state_buy' %}" role="button">Eu
                        quero comprar</a>
                </div>
                <div class="col-md-3">
                    <a class="btn center-block btn-primary btn-lg" href="{% url 'catalog:list_real_state_rent' %}"
                       role="button">Eu quero alugar</a>
                </div>
            </div>
        </div>

    </div>

    <div id="home-broker-call">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center">Corretor? Anuncie já!</h2>
                    <div class="col-md-6 col-md-offset-3">
                        <a class="btn center-block btn-success btn-lg" href="#" role="button">Anunciar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="cities-container" class="container marketing">
        {% if grouped_cities.count %}
            <div class="row">
                <h2 class="text-center">Encontre o imóvel dos sonhos na sua cidade</h2>
                <br><br>
            </div>

            <div class="row cities-row">
                {% for city_list in grouped_cities %}
                    <div class="col-md-4">
                        <ul class="list-unstyled text-center">
                            {% for city in city_list %}
                                <li><a href="{{ city.get_search_url }}">{{ city }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div><!-- /.container -->

{% endblock %}

core/templates/nav.html
<nav class="navbar navbar-default navbar-static-top navbar-imovel-web">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">ImovelWeb</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li><a href="{% url 'catalog:list_real_state_buy' %}">Comprar</a></li>
                <li><a href="{% url 'catalog:list_real_state_rent' %}">Alugar</a></li>
                <li><a href="#">Anunciar</a></li>

                {% if not user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Registrar-se</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:index' %}">Minha Conta</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
                {% endif %}


            </ul>
        </div>
        <!--/.navbar-collapse -->
    </div>
</nav>